// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/google/uuid"
)

type SubscriberAuthor struct {
	SubID  uuid.UUID
	AuthID uuid.UUID
}

type User struct {
	ID           uuid.UUID
	Login        string
	Email        string
	PasswordHash string
}
