// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package database

import (
	"context"

	"github.com/KShekhurin/blog-go/internal/webModels"
	"github.com/google/uuid"
)

const addToOutbox = `-- name: AddToOutbox :exec
INSERT INTO outbox
    (message_type, payload)
VALUES
    ($1, $2)
`

type AddToOutboxParams struct {
	MessageType OutboxMessageType
	Payload     *webModels.Post
}

func (q *Queries) AddToOutbox(ctx context.Context, arg AddToOutboxParams) error {
	_, err := q.db.Exec(ctx, addToOutbox, arg.MessageType, arg.Payload)
	return err
}

const getOutboxEvents = `-- name: GetOutboxEvents :many
SELECT id, message_type, payload, created_at, processed_at FROM outbox
WHERE procesed_at IS NULL
LIMIT $1
`

func (q *Queries) GetOutboxEvents(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.MessageType,
			&i.Payload,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventsAsProcessed = `-- name: SetEventsAsProcessed :exec
UPDATE outbox
SET procesed_at = now()
WHERE id = ANY($1::uuid[])
`

func (q *Queries) SetEventsAsProcessed(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, setEventsAsProcessed, dollar_1)
	return err
}
