// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPost = `-- name: AddPost :exec
INSERT INTO posts
    (id, author_id, reply_to, content, created_at, deleted_at)
VALUES
    ($1, $2, $3, $4, $5, $6)
`

type AddPostParams struct {
	ID        uuid.UUID
	AuthorID  uuid.UUID
	ReplyTo   uuid.NullUUID
	Content   string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) AddPost(ctx context.Context, arg AddPostParams) error {
	_, err := q.db.Exec(ctx, addPost,
		arg.ID,
		arg.AuthorID,
		arg.ReplyTo,
		arg.Content,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	return err
}

const addPostMedia = `-- name: AddPostMedia :exec
INSERT INTO post_media
    (id, post_id, type, mime_type, url, display_order)
VALUES
    ($1, $2, $3, $4, $5, $6)
`

type AddPostMediaParams struct {
	ID           uuid.UUID
	PostID       uuid.UUID
	Type         MediaType
	MimeType     string
	Url          string
	DisplayOrder int32
}

func (q *Queries) AddPostMedia(ctx context.Context, arg AddPostMediaParams) error {
	_, err := q.db.Exec(ctx, addPostMedia,
		arg.ID,
		arg.PostID,
		arg.Type,
		arg.MimeType,
		arg.Url,
		arg.DisplayOrder,
	)
	return err
}

const deletePost = `-- name: DeletePost :execrows
UPDATE posts
SET deleted_at = $2
WHERE id = $1
`

type DeletePostParams struct {
	ID        uuid.UUID
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePost, arg.ID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findLinkedPostMedia = `-- name: FindLinkedPostMedia :many
SELECT id, post_id, type, mime_type, url, display_order FROM post_media
    WHERE post_id = $1
`

func (q *Queries) FindLinkedPostMedia(ctx context.Context, postID uuid.UUID) ([]PostMedium, error) {
	rows, err := q.db.Query(ctx, findLinkedPostMedia, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostMedium
	for rows.Next() {
		var i PostMedium
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Type,
			&i.MimeType,
			&i.Url,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPostById = `-- name: FindPostById :one
SELECT id, author_id, reply_to, content, created_at, deleted_at FROM posts
WHERE id = $1 LIMIT 1
`

func (q *Queries) FindPostById(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, findPostById, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ReplyTo,
		&i.Content,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findPostsByIds = `-- name: FindPostsByIds :many
SELECT id, author_id, reply_to, content, created_at, deleted_at FROM posts
    WHERE id = ANY($1::uuid[])
    AND deleted_at IS NULL
`

func (q *Queries) FindPostsByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Post, error) {
	rows, err := q.db.Query(ctx, findPostsByIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.ReplyTo,
			&i.Content,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPostsMedias = `-- name: FindPostsMedias :many
SELECT id, post_id, type, mime_type, url, display_order FROM post_media
    WHERE post_id = ANY($1::uuid[])
`

func (q *Queries) FindPostsMedias(ctx context.Context, dollar_1 []uuid.UUID) ([]PostMedium, error) {
	rows, err := q.db.Query(ctx, findPostsMedias, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostMedium
	for rows.Next() {
		var i PostMedium
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Type,
			&i.MimeType,
			&i.Url,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserPosts = `-- name: FindUserPosts :many
SELECT id, author_id, reply_to, content, created_at, deleted_at FROM posts
    WHERE author_id = $1
      AND deleted_at IS NULL
    ORDER BY created_at DESC, id DESC
    LIMIT $2
`

type FindUserPostsParams struct {
	AuthorID uuid.UUID
	Limit    int32
}

func (q *Queries) FindUserPosts(ctx context.Context, arg FindUserPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, findUserPosts, arg.AuthorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.ReplyTo,
			&i.Content,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserPostsWithCursor = `-- name: FindUserPostsWithCursor :many
SELECT id, author_id, reply_to, content, created_at, deleted_at FROM posts
    WHERE author_id = $1
      AND deleted_at IS NULL
      AND (created_at, id) < ($3, $4::uuid)
    ORDER BY created_at DESC, id DESC
    LIMIT $2
`

type FindUserPostsWithCursorParams struct {
	AuthorID      uuid.UUID
	Limit         int32
	LastCreatedAt pgtype.Timestamptz
	LastID        uuid.UUID
}

func (q *Queries) FindUserPostsWithCursor(ctx context.Context, arg FindUserPostsWithCursorParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, findUserPostsWithCursor,
		arg.AuthorID,
		arg.Limit,
		arg.LastCreatedAt,
		arg.LastID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.ReplyTo,
			&i.Content,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
