// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRefreshToken = `-- name: AddRefreshToken :exec
INSERT INTO allowed_refresh_tokens
    (jti, user_id, expires_at) VALUES ($1, $2, $3)
`

type AddRefreshTokenParams struct {
	Jti       uuid.UUID
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) AddRefreshToken(ctx context.Context, arg AddRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, addRefreshToken, arg.Jti, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteAllRefreshTokensByUserId = `-- name: DeleteAllRefreshTokensByUserId :exec
DELETE FROM allowed_refresh_tokens
    WHERE user_id = $1
`

func (q *Queries) DeleteAllRefreshTokensByUserId(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllRefreshTokensByUserId, userID)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :execrows
DELETE FROM allowed_refresh_tokens
    WHERE jti = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, jti uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefreshToken, jti)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
