// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addUser = `-- name: AddUser :exec
INSERT INTO users (id, login, email, password_hash)
       VALUES ($1, $2, $3, $4)
`

type AddUserParams struct {
	ID           uuid.UUID
	Login        string
	Email        string
	PasswordHash string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.Exec(ctx, addUser,
		arg.ID,
		arg.Login,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, login, email, password_hash FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT id, login, email, password_hash FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) FindUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const findUserByLogin = `-- name: FindUserByLogin :one
SELECT id, login, email, password_hash FROM users
WHERE login = $1 LIMIT 1
`

func (q *Queries) FindUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const findUserByLoginOrEmail = `-- name: FindUserByLoginOrEmail :one
SELECT id, login, email, password_hash FROM users
WHERE login = $1 OR email = $2 LIMIT 1
`

type FindUserByLoginOrEmailParams struct {
	Login string
	Email string
}

func (q *Queries) FindUserByLoginOrEmail(ctx context.Context, arg FindUserByLoginOrEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, findUserByLoginOrEmail, arg.Login, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getSubscribers = `-- name: GetSubscribers :many
SELECT sub_id FROM subscriber_author
              WHERE auth_id = $1
`

func (q *Queries) GetSubscribers(ctx context.Context, authID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getSubscribers, authID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var sub_id uuid.UUID
		if err := rows.Scan(&sub_id); err != nil {
			return nil, err
		}
		items = append(items, sub_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscribeUserTo = `-- name: SubscribeUserTo :exec
INSERT INTO subscriber_author (sub_id, auth_id)
       VALUES ($1, $2)
`

type SubscribeUserToParams struct {
	SubID  uuid.UUID
	AuthID uuid.UUID
}

func (q *Queries) SubscribeUserTo(ctx context.Context, arg SubscribeUserToParams) error {
	_, err := q.db.Exec(ctx, subscribeUserTo, arg.SubID, arg.AuthID)
	return err
}

const unsubscribeUserFrom = `-- name: UnsubscribeUserFrom :exec
DELETE FROM subscriber_author
       WHERE sub_id = $1 AND auth_id = $2
`

type UnsubscribeUserFromParams struct {
	SubID  uuid.UUID
	AuthID uuid.UUID
}

func (q *Queries) UnsubscribeUserFrom(ctx context.Context, arg UnsubscribeUserFromParams) error {
	_, err := q.db.Exec(ctx, unsubscribeUserFrom, arg.SubID, arg.AuthID)
	return err
}
