// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "An API route to login an user, on success returns access/refresh jwt pair\nEther login or email is required",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login with existing user",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "user_data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webModels.UserLoginInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webModels.TokenPair"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "An API route to register a new user, on success returns access/refresh jwt pair",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration payload",
                        "name": "user_data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webModels.UserRegisterInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webModels.TokenPair"
                        }
                    }
                }
            }
        },
        "/post": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "An API route to send a post, requires an access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Send a post from the user",
                "parameters": [
                    {
                        "description": "Post payload",
                        "name": "post_data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webModels.CreatePostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webModels.Post"
                        }
                    }
                }
            }
        },
        "/user/{user_id}/posts": {
            "get": {
                "description": "An API route to get the user's post, on consecutive requests pass the cursor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts"
                ],
                "summary": "Get posts from the user",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Post cnt limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webModels.PostPaginationResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "webModels.AttachedMedia": {
            "type": "object",
            "properties": {
                "display_order": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "mime_type": {
                    "type": "string"
                },
                "post_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "webModels.CreateAttachedMedia": {
            "type": "object",
            "required": [
                "display_order",
                "mime_type",
                "type",
                "url"
            ],
            "properties": {
                "display_order": {
                    "type": "integer",
                    "minimum": 0
                },
                "mime_type": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "webModels.CreatePostRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "attached": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webModels.CreateAttachedMedia"
                    }
                },
                "content": {
                    "type": "string"
                },
                "reply_to": {
                    "type": "string"
                }
            }
        },
        "webModels.Post": {
            "type": "object",
            "properties": {
                "attached": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webModels.AttachedMedia"
                    }
                },
                "author_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "reply_to": {
                    "type": "string"
                }
            }
        },
        "webModels.PostPaginationResponse": {
            "type": "object",
            "properties": {
                "cursor": {
                    "type": "string"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webModels.Post"
                    }
                }
            }
        },
        "webModels.TokenPair": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "webModels.UserLoginInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "webModels.UserRegisterInfo": {
            "type": "object",
            "required": [
                "email",
                "login",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:9090",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Blog API",
	Description:      "This is the example of a twitter-like blog written on go",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
