name: Enforce Target Branches

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Source Branch
        if: github.head_ref != 'develop'
        run: |
          echo "ERROR: Pull requests to 'main' are only allowed from the 'develop' branch."
          echo "Your current source branch is '${{ github.head_ref }}'."
          exit 1